### ISSUE TITLE
ImportError: cannot import name 'wrap_model' from 'comfy.samplers'

### ISSUE THREAD

**Issue by Davikar** [jags111/efficiency-nodes-comfyui#150]
One of the more recent updates have broken Efficiency nodes and it fails to load.

```
Traceback (most recent call last):
  File "C:\AI\ComfyUI\ComfyUI\nodes.py", line 1889, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui\__init__.py", line 9, in <module>
    from  .efficiency_nodes import NODE_CLASS_MAPPINGS
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 46, in <module>
    from .py import smZ_cfg_denoiser
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui\py\smZ_cfg_denoiser.py", line 7, in <module>
    from comfy.samplers import KSampler, KSamplerX0Inpaint, wrap_model
ImportError: cannot import name 'wrap_model' from 'comfy.samplers' (C:\AI\ComfyUI\ComfyUI\comfy\samplers.py)
```

**Comment by 0wenwenwen0** [comment]
+1

**Comment by 0wenwenwen0** [comment]
File "H:\Comfyui_2\ComfyUI\nodes.py", line 1889, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\Comfyui_2\ComfyUI\custom_nodes\efficiency-nodes-comfyui\__init__.py", line 9, in <module>
    from  .efficiency_nodes import NODE_CLASS_MAPPINGS
  File "H:\Comfyui_2\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 46, in <module>
    from .py import smZ_cfg_denoiser
  File "H:\Comfyui_2\ComfyUI\custom_nodes\efficiency-nodes-comfyui\py\smZ_cfg_denoiser.py", line 7, in <module>
    from comfy.samplers import KSampler, KSamplerX0Inpaint, wrap_model
ImportError: cannot import name 'wrap_model' from 'comfy.samplers' (H:\Comfyui_2\ComfyUI\comfy\samplers.py)

Cannot import H:\Comfyui_2\ComfyUI\custom_nodes\efficiency-nodes-comfyui module for custom nodes: cannot import name 'wrap_model' from 'comfy.samplers' (H:\Comfyui_2\ComfyUI\comfy\samplers.py)

**Comment by RangerFrank** [comment]
+1

Traceback (most recent call last):
  File "D:\AI\ComfyUI\ComfyUI\nodes.py", line 1889, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui\__init__.py", line 9, in <module>
    from  .efficiency_nodes import NODE_CLASS_MAPPINGS
  File "D:\AI\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 46, in <module>
    from .py import smZ_cfg_denoiser
  File "D:\AI\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui\py\smZ_cfg_denoiser.py", line 7, in <module>
    from comfy.samplers import KSampler, KSamplerX0Inpaint, wrap_model
ImportError: cannot import name 'wrap_model' from 'comfy.samplers' (D:\AI\ComfyUI\ComfyUI\comfy\samplers.py)

**Comment by Evilinside3357** [comment]
+1 Same problem here

**Comment by taconugget** [comment]
Same issues in Ubuntu

`Traceback (most recent call last):
  File "/home/zvi/ComfyUI/nodes.py", line 1889, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/zvi/ComfyUI/custom_nodes/efficiency-nodes-comfyui/__init__.py", line 9, in <module>
    from  .efficiency_nodes import NODE_CLASS_MAPPINGS
  File "/home/zvi/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 46, in <module>
    from .py import smZ_cfg_denoiser
  File "/home/zvi/ComfyUI/custom_nodes/efficiency-nodes-comfyui/py/smZ_cfg_denoiser.py", line 7, in <module>
    from comfy.samplers import KSampler, KSamplerX0Inpaint, wrap_model
ImportError: cannot import name 'wrap_model' from 'comfy.samplers' (/home/zvi/ComfyUI/comfy/samplers.py)`

**Comment by jags111** [comment]
hai all due to some changes in code i am updating it

**Comment by JanneN9** [comment]
File: smZ_cfg_denoiser.py
from comfy.samplers import KSampler, KSamplerX0Inpaint
 - remove wrap_model
Two Lines:
self.model_wrap = wrap_model(self.model_denoise)
-> self.model_wrap = self.denoise(model_wrap, sigmas)

**Comment by jags111** [comment]
Okay I patched it. can you please check same
 and if any errors please report . Thanks to everyone.

**Comment by octoworld** [comment]
Still the same error for me:

`Traceback (most recent call last):
  File "C:\Users\xyz\ComfyUI\ComfyUI\nodes.py", line 1889, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\xyz\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui\__init__.py", line 9, in <module>
    from  .efficiency_nodes import NODE_CLASS_MAPPINGS
  File "C:\Users\xyz\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 46, in <module>
    from .py import smZ_cfg_denoiser
  File "C:\Users\xyz\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui\py\smZ_cfg_denoiser.py", line 7, in <module>
    from comfy.samplers import KSampler, KSamplerX0Inpaint, wrap_model
ImportError: cannot import name 'wrap_model' from 'comfy.samplers' (C:\Users\xyz\ComfyUI\ComfyUI\comfy\samplers.py)

Cannot import C:\Users\xyz\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui module for custom nodes: cannot import name 'wrap_model' from 'comfy.samplers' (C:\Users\xyz\ComfyUI\ComfyUI\comfy\samplers.py)`

**Comment by MicPec** [comment]
Still the same, after update:

Traceback (most recent call last):
  File "/run/media/AI/StabilityMatrix-linux-x64/Data/Packages/ComfyUI/nodes.py", line 1889, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/run/media/AI/StabilityMatrix-linux-x64/Data/Packages/ComfyUI/custom_nodes/efficiency-nodes-comfyui/__init__.py", line 9, in <module>
    from  .efficiency_nodes import NODE_CLASS_MAPPINGS
  File "/run/media/AI/StabilityMatrix-linux-x64/Data/Packages/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 46, in <module>
    from .py import smZ_cfg_denoiser
  File "/run/media/AI/StabilityMatrix-linux-x64/Data/Packages/ComfyUI/custom_nodes/efficiency-nodes-comfyui/py/smZ_cfg_denoiser.py", line 7, in <module>
    from comfy.samplers import KSampler, KSamplerX0Inpaint, wrap_model
ImportError: cannot import name 'wrap_model' from 'comfy.samplers' (/run/media/AI/StabilityMatrix-linux-x64/Data/Packages/ComfyUI/comfy/samplers.py)

Cannot import /run/media/AI/StabilityMatrix-linux-x64/Data/Packages/ComfyUI/custom_nodes/efficiency-nodes-comfyui module for custom nodes: cannot import name 'wrap_model' from 'comfy.samplers' (/run/media/AI/StabilityMatrix-linux-x64/Data/Packages/ComfyUI/comfy/samplers.py)

**Comment by taconugget** [comment]
> Okay I patched it. can you please check same and if any errors please report . Thanks to everyone.

Still seeing the same error on my end as well with Ubuntu... Thanks for trying to path it so fast!

`Traceback (most recent call last):
  File "/home/zvi/ComfyUI/nodes.py", line 1889, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/zvi/ComfyUI/custom_nodes/efficiency-nodes-comfyui/__init__.py", line 9, in <module>
    from  .efficiency_nodes import NODE_CLASS_MAPPINGS
  File "/home/zvi/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 46, in <module>
    from .py import smZ_cfg_denoiser
  File "/home/zvi/ComfyUI/custom_nodes/efficiency-nodes-comfyui/py/smZ_cfg_denoiser.py", line 7, in <module>
    from comfy.samplers import KSampler, KSamplerX0Inpaint, wrap_model
ImportError: cannot import name 'wrap_model' from 'comfy.samplers' (/home/zvi/ComfyUI/comfy/samplers.py)`

**Comment by octoworld** [comment]
got it working with a terrible workaround, deleted the content of  smZ_cfg_denoiser.py to just:

```
# https://github.com/shiimizu/ComfyUI_smZNodes
import comfy
```
won't work for everyone but comfyui now running ok with the efficiency nodes i use.

**Comment by RangerFrank** [comment]
This is now working again for me. Great work. Thanks for the speedy response.

**Comment by taconugget** [comment]
Yes, seems another update has come in. This one is working. Thanks @jags111

**Comment by Davikar** [comment]
Yes, it's working again now. 👍

**Comment by TigoTin** [comment]
Still the same now:
`Traceback (most recent call last):
  File "/root/tmp-disk/ComfyUI/nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/tmp-disk/ComfyUI/custom_nodes/efficiency-nodes-comfyui/__init__.py", line 9, in <module>
    from  .efficiency_nodes import NODE_CLASS_MAPPINGS
  File "/root/tmp-disk/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 46, in <module>
    from .py import smZ_cfg_denoiser
  File "/root/tmp-disk/ComfyUI/custom_nodes/efficiency-nodes-comfyui/py/smZ_cfg_denoiser.py", line 7, in <module>
    from comfy.samplers import KSampler, KSamplerX0Inpaint, wrap_model
ImportError: cannot import name 'wrap_model' from 'comfy.samplers' (/root/tmp-disk/ComfyUI/comfy/samplers.py)

Cannot import /root/tmp-disk/ComfyUI/custom_nodes/efficiency-nodes-comfyui module for custom nodes: cannot import name 'wrap_model' from 'comfy.samplers' (/root/tmp-disk/ComfyUI/comfy/samplers.py)`

**Comment by Davikar** [comment]
@TigoTin You need to update your custom nodes. This issue has been fixed and nothing has changed since then.

**Comment by chieeo** [comment]
still the same+1

Cannot import C:\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui module for custom nodes: cannot import name 'wrap_model' from 'comfy.samplers' (C:\ComfyUI-aki-v1.3\comfy\samplers.py)

**Comment by leaveblackgithub** [comment]
> File: smZ_cfg_denoiser.py from comfy.samplers import KSampler, KSamplerX0Inpaint
> 
> * remove wrap_model
>   Two Lines:
>   self.model_wrap = wrap_model(self.model_denoise)
>   -> self.model_wrap = self.denoise(model_wrap, sigmas)

still the same +1, fix manually as intructed above.

**Comment by leaveblackgithub** [comment]
> > File: smZ_cfg_denoiser.py from comfy.samplers import KSampler, KSamplerX0Inpaint
> > 
> > * remove wrap_model
> >   Two Lines:
> >   self.model_wrap = wrap_model(self.model_denoise)
> >   -> self.model_wrap = self.denoise(model_wrap, sigmas)
> 
> still the same +1, fix manually as intructed above.

I double checked the file online. They are actually correct. But somehow my comfy manager always pull wrong version. I finally download the file to overwrite it.

**Comment by zhouyihe** [comment]
“ File "C:\AI\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui\py\smZ_cfg_denoiser.py", line 7, in <module>
    from comfy.samplers import KSampler, KSamplerX0Inpaint, wrap_model”
I ran into the same problem, and my solution was to remove the reference to "wrap_model" from the code. Because I don't see the "wrap_model" attribute in the file "comfy.samplers". I hope I can help others with the same problem.
