### ISSUE TITLE
XY Plot compatibility issues with IPAdapter

### ISSUE THREAD

**Issue by gabperry** [jags111/efficiency-nodes-comfyui#173]
I don't know, if this is about IPAdapter or Efficient Nodes, but when I connect an XY Plot, it actually bypasses all the IPAdapter nodes, and generates image without using them. If I mute XY plot and it's inputs, it generates the image as it should, using IPAdapter nodes. Tested it as i bypassed manually all IPAdapter nodes, and its generates exactly the same image as it generates when XY Plot is connected.

**Comment by techzuhaib** [comment]
Yes same issue

**Comment by jags111** [comment]
ok will test this and will be nice to see the workflow where this occurs so can reproduce same. share if you can.

**Comment by techzuhaib** [comment]
Thanks, I think it's fixed now

**Comment by jffaust** [comment]
@jags111 Can you reopen this? I'm still having issues with the XY Plot and IPAdapter but upon further testing, it seems to only ignore the IPAdapter when using a checkpoint XY input. Here's the workflow I'm using for testing.
[xy-ipadapter-repro.json](https://github.com/user-attachments/files/16324999/xy-ipadapter-repro.json)

When we use a checkpoint XY input, the IPAdapter is ignored:
![image](https://github.com/user-attachments/assets/3e166ff0-7ff4-49a2-b4d6-238e6518251b)

When using other inputs, the IPAdapter works as expexted:
![image](https://github.com/user-attachments/assets/34a4059f-a93e-4a5e-bce0-9a0e2a9f5f94)
